# Site
repository: nguyennth/resume
favicon: images/favicon.ico

# Personal info
name: Nhung T.H. Nguyen
title: Scientist in NLP
email: NNguye63@its.jnj.com
website: https://nguyennth.github.io/

# Social links
twitter_username: nguyenthnhung
github_username:  nguyennth
linkedin_username: nguyenthnhung

# About Section
# about_title: About Me
about_profile_image: images/avatar.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Nhung (the Nh is pronounced like Ñ in Spanish). I'm now a Scientist in NLP at [Johnson & Johnson Innovative Medicine](https://www.janssen.com/johnson-johnson-innovative-medicine). Prior to this, I was a presidential fellow at the Deparment of Computer Science, Faculty of Science and Engineering, University of Manchester. 
 
  My main research is about text mining and natural language processing in the biomedical domain.

  My publications are listed [here](https://scholar.google.co.uk/citations?hl=en&user=UY3KrtIAAAAJ&view_op=list_works&sortby=pubdate).
# Projects Section
# projects_title: Past Projects

# Experience Section
# experience_title: Experience

# Publications Section
# publications_tilte: Publications

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my interests and hobbies are:
   - Travelling
   - Plants
   - Making hand-crafted things
   - Reading books (although I read them very slowly)
   - Swimming (although I'm just a novice swimmer)
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
