# Site
repository: nguyennth/resume
favicon: images/favicon.ico

# Personal info
name: Nhung T.H. Nguyen
title: Presidential Fellow
email: nhung.nguyen@manchester.ac.uk
website: https://nguyennth.github.io/

# Social links
twitter_username: nguyenthnhung
github_username:  nguyennth
linkedin_username: nguyenthnhung

# About Section
# about_title: About Me
about_profile_image: images/avatar.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Nhung (the Nh is pronounced like Ñ in Spanish). I'm now a presidential fellow at the Deparment of Computer Science, Faculty of Science and Engineering, University of Manchester. I'm currently located at [National Center for Text Mining (NaCTeM)](http://nactem.ac.uk/).
 
  My main research is about text mining and natural language processing in biomedical domain.

  My publications are listed [here](https://scholar.google.co.uk/citations?hl=en&user=UY3KrtIAAAAJ&view_op=list_works&sortby=pubdate).
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Publications Section
# publications_tilte: Publications

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my interests and hobbies are:
   - Travelling (apparently this is not a good one in this situation)
   - Plants
   - Making hand-crafted things
   - Reading books (although I read them very slowly)
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
